### ISSUE TITLE
Request: code example for javascript browser azure speech recognition

### ISSUE THREAD

**Issue by inglesuniversal** [compulim/web-speech-cognitive-services#112]
Your example code shows some code for node.js, do you have an example available for the browser (using the mic and a javascript library inside a script tag search element?)

The examples at azure github repository are way to long just to detect the voice.

thanks and stay safe.

**Comment by compulim** [comment]
This is a polyfill for W3C Web Speech API using Azure Cognitive Services. This library does NOT work in Node.js. It only works in browser.

You can find some Web Speech API samples from MDN. Instead of using `window.SpeechRecognition`, use the `SpeechRecognition` provided by this library, everything will work seamlessly.

https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API/Using_the_Web_Speech_API
